var wordArry=[["ancient","éinʃənt","고대의"],["Egyptian","idʒípʃən","이집트 사람"],
              ["dead","ded","죽은"],["into","íntu","안으로"],
              ["mummy","mʌ́m","미라"],["preserve","prizə́ːr","지키다"],
              ["ruler","rúːlǝr","통치자"],["pharaoh","fέərou","파라오"],
              ["believe","bilíːv","믿다"],["hought","θɔːt","생각했다"],
              ["flow","flou","흐르다"],["crop","krɑp","(농)작물"],
              ["northeast","nɔ̀ːrθíːs","북동쪽"],["northward","nɔ́ːrθwǝr","북쪽으로"],
              ["through","θruː","~통해서"],["Mediterranean","mèdǝtǝréiniǝn","지중해의"],
              ["visitor","vízitǝr","방문객"],["knelt","nelt","무릎을 꿇다"],
              ["honor","άnǝr","존경하다"],["body","bάdi","시신"],
              ["waste","weist","낭비하다"],["poem","póuim","시"],
              ["whisper","hwíspǝr","속삭이다"],["amazing","ǝméiziŋ","놀랄만한"],
              ["participate","pɑːrtísǝpèit","참여하다"],["rude","ruːd","버릇없는"],
              ["dull","dʌl","무딘"],["press","pres","누르다"],
              ["secret","síːkrit","비밀"],["awesome","ɔ́ːsǝ","장엄한"],
              ["soldier","sóuldʒǝr","군인"],["collect","kǝlékt","수집하다"],
              ["route","ruːt","길"],["culture","kʌ́ltʃǝ","문화"],
              ["system","sístǝm","체계"],["popular","pάpjǝlǝr","인기 있는"],
              ["worship","wə́ːrʃi","숭배하다"],["control","kǝntróul","통치하다"],
              ["form","fɔːrm","유형"],["several","sévərǝl","몇의"],
              ["shown","ʃoun","보여준"],["falcon","fǽlkǝn","매"],
              ["person","pə́ːrsə","사람"],["lead","liːd","안내하다"],
              ["soul","soul","영혼"],["tomb","tuːm","무덤"],
              ["toward","tɔːrd","~쪽으로"],["seat","seat","앉히다"],
              ["decay","dikéi","부패하다"],["forever","fǝrévǝr","영원히"],         //63번까지
			  ["ancient","éinʃənt","고대의"],["Egyptian","idʒípʃən","이집트 사람"],
              ["dead","ded","죽은"],["into","íntu","안으로"],
              ["mummy","mʌ́m","미라"],["preserve","prizə́ːr","지키다"],
              ["ruler","rúːlǝr","통치자"],["pharaoh","fέərou","파라오"],
              ["believe","bilíːv","믿다"],["hought","θɔːt","생각했다"],
              ["flow","flou","흐르다"],["crop","krɑp","(농)작물"],
              ["northeast","nɔ̀ːrθíːs","북동쪽"],["northward","nɔ́ːrθwǝr","북쪽으로"],
              ["through","θruː","~통해서"],["Mediterranean","mèdǝtǝréiniǝn","지중해의"],
              ["visitor","vízitǝr","방문객"],["knelt","nelt","무릎을 꿇다"],
              ["honor","άnǝr","존경하다"],["body","bάdi","시신"],
              ["waste","weist","낭비하다"],["poem","póuim","시"],
              ["whisper","hwíspǝr","속삭이다"],["amazing","ǝméiziŋ","놀랄만한"],
              ["participate","pɑːrtísǝpèit","참여하다"],["rude","ruːd","버릇없는"],
              ["dull","dʌl","무딘"],["press","pres","누르다"],
              ["secret","síːkrit","비밀"],["awesome","ɔ́ːsǝ","장엄한"],
              ["soldier","sóuldʒǝr","군인"],["collect","kǝlékt","수집하다"],
              ["route","ruːt","길"],["culture","kʌ́ltʃǝ","문화"],
              ["system","sístǝm","체계"],["popular","pάpjǝlǝr","인기 있는"],
              ["worship","wə́ːrʃi","숭배하다"],["control","kǝntróul","통치하다"],
              ["form","fɔːrm","유형"],["several","sévərǝl","몇의"],
              ["shown","ʃoun","보여준"],["falcon","fǽlkǝn","매"],
              ["person","pə́ːrsə","사람"],["lead","liːd","안내하다"],
              ["soul","soul","영혼"],["tomb","tuːm","무덤"],
              ["toward","tɔːrd","~쪽으로"],["seat","seat","앉히다"],
              ["decay","dikéi","부패하다"],["forever","fǝrévǝr","영원히"],
			  ["ancient","éinʃənt","고대의"],["Egyptian","idʒípʃən","이집트 사람"],
              ["dead","ded","죽은"],["into","íntu","안으로"],
              ["mummy","mʌ́m","미라"],["preserve","prizə́ːr","지키다"],
              ["ruler","rúːlǝr","통치자"],["pharaoh","fέərou","파라오"],
              ["believe","bilíːv","믿다"],["hought","θɔːt","생각했다"],
              ["flow","flou","흐르다"],["crop","krɑp","(농)작물"],
              ["northeast","nɔ̀ːrθíːs","북동쪽"],["northward","nɔ́ːrθwǝr","북쪽으로"],
              ["through","θruː","~통해서"],["Mediterranean","mèdǝtǝréiniǝn","지중해의"],
              ["visitor","vízitǝr","방문객"],["knelt","nelt","무릎을 꿇다"],
              ["honor","άnǝr","존경하다"],["body","bάdi","시신"],
              ["waste","weist","낭비하다"],["poem","póuim","시"],
              ["whisper","hwíspǝr","속삭이다"],["amazing","ǝméiziŋ","놀랄만한"],
              ["participate","pɑːrtísǝpèit","참여하다"],["rude","ruːd","버릇없는"],
              ["dull","dʌl","무딘"],["press","pres","누르다"],
              ["secret","síːkrit","비밀"],["awesome","ɔ́ːsǝ","장엄한"],
              ["soldier","sóuldʒǝr","군인"],["collect","kǝlékt","수집하다"],
              ["route","ruːt","길"],["culture","kʌ́ltʃǝ","문화"],
              ["system","sístǝm","체계"],["popular","pάpjǝlǝr","인기 있는"],
              ["worship","wə́ːrʃi","숭배하다"],["control","kǝntróul","통치하다"],
              ["form","fɔːrm","유형"],["several","sévərǝl","몇의"],
              ["shown","ʃoun","보여준"],["falcon","fǽlkǝn","매"],
              ["person","pə́ːrsə","사람"],["lead","liːd","안내하다"],
              ["soul","soul","영혼"],["tomb","tuːm","무덤"],
              ["toward","tɔːrd","~쪽으로"],["seat","seat","앉히다"],
              ["decay","dikéi","부패하다"],["forever","fǝrévǝr","영원히"],
			  ["ancient","éinʃənt","고대의"],["Egyptian","idʒípʃən","이집트 사람"],
              ["dead","ded","죽은"],["into","íntu","안으로"],
              ["mummy","mʌ́m","미라"],["preserve","prizə́ːr","지키다"],
              ["ruler","rúːlǝr","통치자"],["pharaoh","fέərou","파라오"],
              ["believe","bilíːv","믿다"],["hought","θɔːt","생각했다"],
              ["flow","flou","흐르다"],["crop","krɑp","(농)작물"],
              ["northeast","nɔ̀ːrθíːs","북동쪽"],["northward","nɔ́ːrθwǝr","북쪽으로"],
              ["through","θruː","~통해서"],["Mediterranean","mèdǝtǝréiniǝn","지중해의"],
              ["visitor","vízitǝr","방문객"],["knelt","nelt","무릎을 꿇다"],
              ["honor","άnǝr","존경하다"],["body","bάdi","시신"],
              ["waste","weist","낭비하다"],["poem","póuim","시"],
              ["whisper","hwíspǝr","속삭이다"],["amazing","ǝméiziŋ","놀랄만한"],
              ["participate","pɑːrtísǝpèit","참여하다"],["rude","ruːd","버릇없는"],
              ["dull","dʌl","무딘"],["press","pres","누르다"],
              ["secret","síːkrit","비밀"],["awesome","ɔ́ːsǝ","장엄한"],
              ["soldier","sóuldʒǝr","군인"],["collect","kǝlékt","수집하다"],
              ["route","ruːt","길"],["culture","kʌ́ltʃǝ","문화"],
              ["system","sístǝm","체계"],["popular","pάpjǝlǝr","인기 있는"],
              ["worship","wə́ːrʃi","숭배하다"],["control","kǝntróul","통치하다"],
              ["form","fɔːrm","유형"],["several","sévərǝl","몇의"],
              ["shown","ʃoun","보여준"],["falcon","fǽlkǝn","매"],
              ["person","pə́ːrsə","사람"],["lead","liːd","안내하다"],
              ["soul","soul","영혼"],["tomb","tuːm","무덤"],
              ["toward","tɔːrd","~쪽으로"],["seat","seat","앉히다"],
              ["decay","dikéi","부패하다"],["forever","fǝrévǝr","영원히"],
			  ["ancient","éinʃənt","고대의"],["Egyptian","idʒípʃən","이집트 사람"],
              ["dead","ded","죽은"],["into","íntu","안으로"],
              ["mummy","mʌ́m","미라"],["preserve","prizə́ːr","지키다"],
              ["ruler","rúːlǝr","통치자"],["pharaoh","fέərou","파라오"],
              ["believe","bilíːv","믿다"],["hought","θɔːt","생각했다"],
              ["flow","flou","흐르다"],["crop","krɑp","(농)작물"],
              ["northeast","nɔ̀ːrθíːs","북동쪽"],["northward","nɔ́ːrθwǝr","북쪽으로"],
              ["through","θruː","~통해서"],["Mediterranean","mèdǝtǝréiniǝn","지중해의"],
              ["visitor","vízitǝr","방문객"],["knelt","nelt","무릎을 꿇다"],
              ["honor","άnǝr","존경하다"],["body","bάdi","시신"],
              ["waste","weist","낭비하다"],["poem","póuim","시"],
              ["whisper","hwíspǝr","속삭이다"],["amazing","ǝméiziŋ","놀랄만한"],
              ["participate","pɑːrtísǝpèit","참여하다"],["rude","ruːd","버릇없는"],
              ["dull","dʌl","무딘"],["press","pres","누르다"],
              ["secret","síːkrit","비밀"],["awesome","ɔ́ːsǝ","장엄한"],
              ["soldier","sóuldʒǝr","군인"],["collect","kǝlékt","수집하다"],
              ["route","ruːt","길"],["culture","kʌ́ltʃǝ","문화"],
              ["system","sístǝm","체계"],["popular","pάpjǝlǝr","인기 있는"],
              ["worship","wə́ːrʃi","숭배하다"],["control","kǝntróul","통치하다"],
              ["form","fɔːrm","유형"],["several","sévərǝl","몇의"],
              ["shown","ʃoun","보여준"],["falcon","fǽlkǝn","매"],
              ["person","pə́ːrsə","사람"],["lead","liːd","안내하다"],
              ["soul","soul","영혼"],["tomb","tuːm","무덤"],
              ["toward","tɔːrd","~쪽으로"],["seat","seat","앉히다"],
              ["decay","dikéi","부패하다"],["forever","fǝrévǝr","영원히"],
			  ["ancient","éinʃənt","고대의"],["Egyptian","idʒípʃən","이집트 사람"],
              ["dead","ded","죽은"],["into","íntu","안으로"],
              ["mummy","mʌ́m","미라"],["preserve","prizə́ːr","지키다"],
              ["ruler","rúːlǝr","통치자"],["pharaoh","fέərou","파라오"],
              ["believe","bilíːv","믿다"],["hought","θɔːt","생각했다"],
              ["flow","flou","흐르다"],["crop","krɑp","(농)작물"],
              ["northeast","nɔ̀ːrθíːs","북동쪽"],["northward","nɔ́ːrθwǝr","북쪽으로"],
              ["through","θruː","~통해서"],["Mediterranean","mèdǝtǝréiniǝn","지중해의"],
              ["visitor","vízitǝr","방문객"],["knelt","nelt","무릎을 꿇다"],
              ["honor","άnǝr","존경하다"],["body","bάdi","시신"],
              ["waste","weist","낭비하다"],["poem","póuim","시"],
              ["whisper","hwíspǝr","속삭이다"],["amazing","ǝméiziŋ","놀랄만한"],
              ["participate","pɑːrtísǝpèit","참여하다"],["rude","ruːd","버릇없는"],
              ["dull","dʌl","무딘"],["press","pres","누르다"],
              ["secret","síːkrit","비밀"],["awesome","ɔ́ːsǝ","장엄한"],
              ["soldier","sóuldʒǝr","군인"],["collect","kǝlékt","수집하다"],
              ["route","ruːt","길"],["culture","kʌ́ltʃǝ","문화"],
              ["system","sístǝm","체계"],["popular","pάpjǝlǝr","인기 있는"],
              ["worship","wə́ːrʃi","숭배하다"],["control","kǝntróul","통치하다"],
              ["form","fɔːrm","유형"],["several","sévərǝl","몇의"],
              ["shown","ʃoun","보여준"],["falcon","fǽlkǝn","매"],
              ["person","pə́ːrsə","사람"],["lead","liːd","안내하다"],
              ["soul","soul","영혼"],["tomb","tuːm","무덤"],
              ["toward","tɔːrd","~쪽으로"],["seat","seat","앉히다"],
              ["decay","dikéi","부패하다"],["forever","fǝrévǝr","영원히"],
			  ["ancient","éinʃənt","고대의"],["Egyptian","idʒípʃən","이집트 사람"],
              ["dead","ded","죽은"],["into","íntu","안으로"],
              ["mummy","mʌ́m","미라"],["preserve","prizə́ːr","지키다"],
              ["ruler","rúːlǝr","통치자"],["pharaoh","fέərou","파라오"],
              ["believe","bilíːv","믿다"],["hought","θɔːt","생각했다"],
              ["flow","flou","흐르다"],["crop","krɑp","(농)작물"],
              ["northeast","nɔ̀ːrθíːs","북동쪽"],["northward","nɔ́ːrθwǝr","북쪽으로"],
              ["through","θruː","~통해서"],["Mediterranean","mèdǝtǝréiniǝn","지중해의"],
              ["visitor","vízitǝr","방문객"],["knelt","nelt","무릎을 꿇다"],
              ["honor","άnǝr","존경하다"],["body","bάdi","시신"],
              ["waste","weist","낭비하다"],["poem","póuim","시"],
              ["whisper","hwíspǝr","속삭이다"],["amazing","ǝméiziŋ","놀랄만한"],
              ["participate","pɑːrtísǝpèit","참여하다"],["rude","ruːd","버릇없는"],
              ["dull","dʌl","무딘"],["press","pres","누르다"],
              ["secret","síːkrit","비밀"],["awesome","ɔ́ːsǝ","장엄한"],
              ["soldier","sóuldʒǝr","군인"],["collect","kǝlékt","수집하다"],
              ["route","ruːt","길"],["culture","kʌ́ltʃǝ","문화"],
              ["system","sístǝm","체계"],["popular","pάpjǝlǝr","인기 있는"],
              ["worship","wə́ːrʃi","숭배하다"],["control","kǝntróul","통치하다"],
              ["form","fɔːrm","유형"],["several","sévərǝl","몇의"],
              ["shown","ʃoun","보여준"],["falcon","fǽlkǝn","매"],
              ["person","pə́ːrsə","사람"],["lead","liːd","안내하다"],
              ["soul","soul","영혼"],["tomb","tuːm","무덤"],
              ["toward","tɔːrd","~쪽으로"],["seat","seat","앉히다"],
              ["decay","dikéi","부패하다"],["forever","fǝrévǝr","영원히"]];
